cloud:
  aws:
    s3:
      bucket: suquiz-bucket
    credentials:
      access-key: AKIAUNQDZ46QMBQG4R5E
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false