jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: 218218ad0178d4a0b76a55ffeb155957
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect: http://localhost:8080/users/logout/kakao
      logout: https://kapi.kakao.com/v1/user/logout
  naver:
    secret: KEbntDhS1I
    client-id: P_LIzqGM9aUsN8YUcWoY
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i10b302.p.ssafy.io:3306/suquiz?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: b302suquiz

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true